### Installing, loading and checking the version of numpy

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [2]:
conda install numpy

Solving environment: ...working... done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.




==> WARNING: A newer version of conda exists. <==
  current version: 23.3.1
  latest version: 23.7.2

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.7.2




In [3]:
!pip install numpy

In [4]:
import numpy as np
np.version.version
np.__version__

'1.23.5'

'1.23.5'

### Creating 1D, 2D and 3D arrays

In [5]:
arr1 = np.array((1,2,3,4,5,6))
arr2 = np.array([1,2,3,4,5,6])
arr1
arr2

array([1, 2, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

In [6]:
array1D = np.array (range(50,100))
array2D = np.arange(50,100).reshape(2,25)
array3D = np.arange(50,100).reshape(5,2,5)
array1D
array2D
array3D

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

array([[[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]],

       [[70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89]],

       [[90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [7]:
array1d = np.array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

array2d = np.array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

array3d = np.array([[[50, 51, 52, 53, 54],
                     [55, 56, 57, 58, 59]],

                    [[60, 61, 62, 63, 64],
                     [65, 66, 67, 68, 69]],

                    [[70, 71, 72, 73, 74],
                     [75, 76, 77, 78, 79]],

                    [[80, 81, 82, 83, 84],
                     [85, 86, 87, 88, 89]],

                    [[90, 91, 92, 93, 94],
                     [95, 96, 97, 98, 99]]])

array1d
array2d
array3d

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

array([[[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]],

       [[70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89]],

       [[90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

### Built-In FUNCTIONS

In [8]:
array1D
array2D
array3D

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

array([[[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]],

       [[70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89]],

       [[90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [9]:
# dtype -----> type of the data used inside the numpy arrays
array1D.dtype
array2D.dtype
array3D.dtype

dtype('int32')

dtype('int32')

dtype('int32')

In [10]:
array1D = np.array (range(50,100), dtype = 'str')
array2D = np.arange(50,100).reshape(2,25)
array3D = np.arange(50,100).reshape(5,2,5)
array1D.dtype
array2D.dtype
array3D.dtype

dtype('<U2')

dtype('int32')

dtype('int32')

In [11]:
# shape -----> structure of the numpy arrays
array1D.shape
array2D.shape
array3D.shape

(50,)

(2, 25)

(5, 2, 5)

In [12]:
# range -----> in between the start and stop values
array1D = np.array (range(50,100))
array2D = np.arange(50,100).reshape(2,25)
array3D = np.arange(50,100).reshape(5,2,5)
array1D
array2D
array3D

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

array([[[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]],

       [[70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89]],

       [[90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [13]:
# range -----> in between the start and stop values with some steps
array1D = np.array (range(50,100,10))
array2D = np.arange(50,100,5).reshape(2,5)
array3D = np.arange(50,100,5).reshape(5,2,1)
array1D
array2D
array3D

array([50, 60, 70, 80, 90])

array([[50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

array([[[50],
        [55]],

       [[60],
        [65]],

       [[70],
        [75]],

       [[80],
        [85]],

       [[90],
        [95]]])

In [14]:
# ndim -----> tells whether it is 1D, 2D, 3D or so on
array1D = np.array (range(50,100))
array2D = np.arange(50,100).reshape(2,25)
array3D = np.arange(50,100).reshape(5,2,5)
array1D.ndim
array2D.ndim
array3D.ndim

1

2

3

In [15]:
# ndmin -----> instruct you to take those dimensions inside the numpy array
array1D = np.array (range(50,100) , ndmin = 25)
array2D = np.arange(50,100).reshape(2,25)
array3D = np.arange(50,100).reshape(5,2,5)
array1D.ndim
array2D.ndim
array3D.ndim

25

2

3

In [16]:
# size -----> total number of elements
array1D = np.array (range(50,100))
array2D = np.arange(50,100).reshape(2,25)
array3D = np.arange(50,100).reshape(5,2,5)
array1D.size
array2D.size
array3D.size

50

50

50

In [17]:
# nbytes -----> total number of bits (1 byte = 4 bits)
array1D = np.array (range(50,100))
array2D = np.arange(50,100).reshape(2,25)
array3D = np.arange(50,100).reshape(5,2,5)
array1D.nbytes
array2D.nbytes
array3D.nbytes

200

200

200

In [18]:
# reshape -----> reshaping the numpy array into requried dimesntions
array1D = np.array (range(50,100))
array2D = np.arange(50,100).reshape(2,25)
array3D = np.arange(50,100).reshape(5,2,5)
array1D.shape
array2D.shape
array3D.shape
array1D
array2D
array3D
array1D = np.array (range(50,100)).reshape (5,5,2)
array1D.shape
array2D.shape
array3D.shape
array1D
array2D
array3D

(50,)

(2, 25)

(5, 2, 5)

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

array([[[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]],

       [[70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89]],

       [[90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

(5, 5, 2)

(2, 25)

(5, 2, 5)

array([[[50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]],

       [[60, 61],
        [62, 63],
        [64, 65],
        [66, 67],
        [68, 69]],

       [[70, 71],
        [72, 73],
        [74, 75],
        [76, 77],
        [78, 79]],

       [[80, 81],
        [82, 83],
        [84, 85],
        [86, 87],
        [88, 89]],

       [[90, 91],
        [92, 93],
        [94, 95],
        [96, 97],
        [98, 99]]])

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

array([[[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]],

       [[70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89]],

       [[90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

### Special Functions

In [19]:
# arange -----> in between the start and stop(excluded) with specified float vlaue steps
array1D = np.array (range(50,100))
array2D = np.arange(50,100,5.2).reshape(2,5)
array3D = np.arange(50,100,5.2).reshape(5,2,1)
array1D
array2D
array3D

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

array([[50. , 55.2, 60.4, 65.6, 70.8],
       [76. , 81.2, 86.4, 91.6, 96.8]])

array([[[50. ],
        [55.2]],

       [[60.4],
        [65.6]],

       [[70.8],
        [76. ]],

       [[81.2],
        [86.4]],

       [[91.6],
        [96.8]]])

In [20]:
# linespace -----> in between the start and stop(included) with specified float vlaue steps
array1 = np.array (range(50,100,10))
array2 = np.linspace(50,100,10).reshape((2,5))
array3 = np.linspace(50,100,5).reshape((5,1))
array1
array2
array3

array([50, 60, 70, 80, 90])

array([[ 50.        ,  55.55555556,  61.11111111,  66.66666667,
         72.22222222],
       [ 77.77777778,  83.33333333,  88.88888889,  94.44444444,
        100.        ]])

array([[ 50. ],
       [ 62.5],
       [ 75. ],
       [ 87.5],
       [100. ]])

In [21]:
# zero -----> np.zeros((r,c)) array with the specified dimensions and data is filled with zeros.
array1D = np.zeros((1,))
array2D = np.zeros((5,2))
array3D = np.zeros((5,2,10))
array1D
array2D
array3D

array([0.])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [22]:
# ones -----> np.ones((r,c)) array with the specified dimensions and data is filled with ones.
array1D = np.ones((1,))
array2D = np.ones((5,2))
array3D = np.ones((5,2,10))
array1D
array2D
array3D

array([1.])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [23]:
# full -----> np.full((r,c),n) array with the specified dimensions and data is filled with n(num/str).
array1D = np.full((1,),'1d')
array2D = np.full((5,2),'2d')
array3D = np.full((5,2,10),'3d')
array1D
array2D
array3D

array(['1d'], dtype='<U2')

array([['2d', '2d'],
       ['2d', '2d'],
       ['2d', '2d'],
       ['2d', '2d'],
       ['2d', '2d']], dtype='<U2')

array([[['3d', '3d', '3d', '3d', '3d', '3d', '3d', '3d', '3d', '3d'],
        ['3d', '3d', '3d', '3d', '3d', '3d', '3d', '3d', '3d', '3d']],

       [['3d', '3d', '3d', '3d', '3d', '3d', '3d', '3d', '3d', '3d'],
        ['3d', '3d', '3d', '3d', '3d', '3d', '3d', '3d', '3d', '3d']],

       [['3d', '3d', '3d', '3d', '3d', '3d', '3d', '3d', '3d', '3d'],
        ['3d', '3d', '3d', '3d', '3d', '3d', '3d', '3d', '3d', '3d']],

       [['3d', '3d', '3d', '3d', '3d', '3d', '3d', '3d', '3d', '3d'],
        ['3d', '3d', '3d', '3d', '3d', '3d', '3d', '3d', '3d', '3d']],

       [['3d', '3d', '3d', '3d', '3d', '3d', '3d', '3d', '3d', '3d'],
        ['3d', '3d', '3d', '3d', '3d', '3d', '3d', '3d', '3d', '3d']]],
      dtype='<U2')

In [24]:
# eye -----> array where all elements are equal to zero,
# except for the k-th diagonal, whose values are equal to one.
# This function creates the identity array
array2D = np.eye(10 , dtype = 'int32')
array2D

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [25]:
# identity -----> generates square array with ones on the main diagonal 
array2D = np.identity(10 , dtype = 'int32')
array2D

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [26]:
# diag() -----> function extract or construct diagonal array.
array2D = np.diag (np.arange(5,20))
array2D

array([[ 5,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  7,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  8,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 11,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 12,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 13,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 14,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 15,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 16,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 17,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 18,  0],
       [ 0,  0,  0,  0,  0,  0,  0

### Indexing and Slicing

In [27]:
array1D = np.array (range(50,100))
array2D = np.arange(50,100).reshape(2,25)
array3D = np.arange(50,100).reshape(5,2,5)
array1D
array2D
array3D

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

array([[[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]],

       [[70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89]],

       [[90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [28]:
array1D
array1D[0]
array1D[-1]
array1D[::5]
array1D[::-10]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

50

99

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

array([99, 89, 79, 69, 59])

In [29]:
array2D
array2D[0:2]
array2D[0:2 , 1]
array2D[0:2][1]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

array([51, 76])

array([75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
       92, 93, 94, 95, 96, 97, 98, 99])

In [30]:
array3D
array3D[0:2]
array3D[0:2 , 1]
array3D[0:2][1]

array([[[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]],

       [[70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89]],

       [[90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

array([[[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

array([[55, 56, 57, 58, 59],
       [65, 66, 67, 68, 69]])

array([[60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69]])

In [31]:
#fliplr -----> flipping in left-right direction
array2D = np.arange(50,100).reshape(2,25)
array3D = np.arange(50,100).reshape(5,2,5)
np.fliplr(array2D)
np.fliplr(array3D)

array([[74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60, 59,
        58, 57, 56, 55, 54, 53, 52, 51, 50],
       [99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84,
        83, 82, 81, 80, 79, 78, 77, 76, 75]])

array([[[55, 56, 57, 58, 59],
        [50, 51, 52, 53, 54]],

       [[65, 66, 67, 68, 69],
        [60, 61, 62, 63, 64]],

       [[75, 76, 77, 78, 79],
        [70, 71, 72, 73, 74]],

       [[85, 86, 87, 88, 89],
        [80, 81, 82, 83, 84]],

       [[95, 96, 97, 98, 99],
        [90, 91, 92, 93, 94]]])

In [32]:
# flipud -----> flipping in up-down direction
array2D = np.arange(50,100).reshape(2,25)
array3D = np.arange(50,100).reshape(5,2,5)
np.flipud(array2D)
np.flipud(array3D)

array([[75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74]])

array([[[90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89]],

       [[70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [33]:
#flip -----> flipping in reverse direction
array2D = np.arange(50,100).reshape(2,25)
array3D = np.arange(50,100).reshape(5,2,5)
np.flip(array2D)
np.flip(array3D)

array([[99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84,
        83, 82, 81, 80, 79, 78, 77, 76, 75],
       [74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60, 59,
        58, 57, 56, 55, 54, 53, 52, 51, 50]])

array([[[99, 98, 97, 96, 95],
        [94, 93, 92, 91, 90]],

       [[89, 88, 87, 86, 85],
        [84, 83, 82, 81, 80]],

       [[79, 78, 77, 76, 75],
        [74, 73, 72, 71, 70]],

       [[69, 68, 67, 66, 65],
        [64, 63, 62, 61, 60]],

       [[59, 58, 57, 56, 55],
        [54, 53, 52, 51, 50]]])

In [34]:
#flip -----> flipping in axis=1 direction
array2D = np.arange(50,100).reshape(2,25)
array3D = np.arange(50,100).reshape(5,2,5)
np.flip(array2D , axis = 1)
np.flip(array3D , axis = 1)

array([[74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60, 59,
        58, 57, 56, 55, 54, 53, 52, 51, 50],
       [99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84,
        83, 82, 81, 80, 79, 78, 77, 76, 75]])

array([[[55, 56, 57, 58, 59],
        [50, 51, 52, 53, 54]],

       [[65, 66, 67, 68, 69],
        [60, 61, 62, 63, 64]],

       [[75, 76, 77, 78, 79],
        [70, 71, 72, 73, 74]],

       [[85, 86, 87, 88, 89],
        [80, 81, 82, 83, 84]],

       [[95, 96, 97, 98, 99],
        [90, 91, 92, 93, 94]]])

In [35]:
#flip -----> flipping in axis=0 direction
array2D = np.arange(50,100).reshape(2,25)
array3D = np.arange(50,100).reshape(5,2,5)
np.flip(array2D , axis = 0)
np.flip(array3D , axis = 0)

array([[75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74]])

array([[[90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89]],

       [[70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [36]:
# transpose -----> changing rows into columns and vice-versa
array1D = np.array (range(50,100))
array2D = np.arange(50,100).reshape(2,25)
array3D = np.arange(50,100).reshape(5,2,5)
array1D.T
array2D.T
array3D.T
np.transpose(array1D)
np.transpose(array2D)
np.transpose(array3D)

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

array([[50, 75],
       [51, 76],
       [52, 77],
       [53, 78],
       [54, 79],
       [55, 80],
       [56, 81],
       [57, 82],
       [58, 83],
       [59, 84],
       [60, 85],
       [61, 86],
       [62, 87],
       [63, 88],
       [64, 89],
       [65, 90],
       [66, 91],
       [67, 92],
       [68, 93],
       [69, 94],
       [70, 95],
       [71, 96],
       [72, 97],
       [73, 98],
       [74, 99]])

array([[[50, 60, 70, 80, 90],
        [55, 65, 75, 85, 95]],

       [[51, 61, 71, 81, 91],
        [56, 66, 76, 86, 96]],

       [[52, 62, 72, 82, 92],
        [57, 67, 77, 87, 97]],

       [[53, 63, 73, 83, 93],
        [58, 68, 78, 88, 98]],

       [[54, 64, 74, 84, 94],
        [59, 69, 79, 89, 99]]])

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

array([[50, 75],
       [51, 76],
       [52, 77],
       [53, 78],
       [54, 79],
       [55, 80],
       [56, 81],
       [57, 82],
       [58, 83],
       [59, 84],
       [60, 85],
       [61, 86],
       [62, 87],
       [63, 88],
       [64, 89],
       [65, 90],
       [66, 91],
       [67, 92],
       [68, 93],
       [69, 94],
       [70, 95],
       [71, 96],
       [72, 97],
       [73, 98],
       [74, 99]])

array([[[50, 60, 70, 80, 90],
        [55, 65, 75, 85, 95]],

       [[51, 61, 71, 81, 91],
        [56, 66, 76, 86, 96]],

       [[52, 62, 72, 82, 92],
        [57, 67, 77, 87, 97]],

       [[53, 63, 73, 83, 93],
        [58, 68, 78, 88, 98]],

       [[54, 64, 74, 84, 94],
        [59, 69, 79, 89, 99]]])

In [37]:
# rot90 -----> changing rows into columns in anti-clockwise direction of 90's
array2D = np.arange(50,100).reshape(2,25)
array3D = np.arange(50,100).reshape(5,2,5)
np.rot90(array2D)
np.rot90(array3D)
np.flipud(np.transpose(array2D))
np.flipud(np.transpose(array3D))

array([[74, 99],
       [73, 98],
       [72, 97],
       [71, 96],
       [70, 95],
       [69, 94],
       [68, 93],
       [67, 92],
       [66, 91],
       [65, 90],
       [64, 89],
       [63, 88],
       [62, 87],
       [61, 86],
       [60, 85],
       [59, 84],
       [58, 83],
       [57, 82],
       [56, 81],
       [55, 80],
       [54, 79],
       [53, 78],
       [52, 77],
       [51, 76],
       [50, 75]])

array([[[55, 56, 57, 58, 59],
        [65, 66, 67, 68, 69],
        [75, 76, 77, 78, 79],
        [85, 86, 87, 88, 89],
        [95, 96, 97, 98, 99]],

       [[50, 51, 52, 53, 54],
        [60, 61, 62, 63, 64],
        [70, 71, 72, 73, 74],
        [80, 81, 82, 83, 84],
        [90, 91, 92, 93, 94]]])

array([[74, 99],
       [73, 98],
       [72, 97],
       [71, 96],
       [70, 95],
       [69, 94],
       [68, 93],
       [67, 92],
       [66, 91],
       [65, 90],
       [64, 89],
       [63, 88],
       [62, 87],
       [61, 86],
       [60, 85],
       [59, 84],
       [58, 83],
       [57, 82],
       [56, 81],
       [55, 80],
       [54, 79],
       [53, 78],
       [52, 77],
       [51, 76],
       [50, 75]])

array([[[54, 64, 74, 84, 94],
        [59, 69, 79, 89, 99]],

       [[53, 63, 73, 83, 93],
        [58, 68, 78, 88, 98]],

       [[52, 62, 72, 82, 92],
        [57, 67, 77, 87, 97]],

       [[51, 61, 71, 81, 91],
        [56, 66, 76, 86, 96]],

       [[50, 60, 70, 80, 90],
        [55, 65, 75, 85, 95]]])

### STATISTICAL FUNCTIONS

In [38]:
# max -----> maximum in array
array1D = np.array (range(50,100))
array2D = np.arange(50,100).reshape(2,25)
array3D = np.arange(50,100).reshape(5,2,5)
array1D.max()
array2D.max()
array3D.max()

99

99

99

In [39]:
# max -----> maximum in array via axis = 1
array1D = np.array (range(50,100))
array2D = np.arange(50,100).reshape(2,25)
array3D = np.arange(50,100).reshape(5,2,5)
array1D.max()
array2D.max(axis = 1)
array3D.max(axis = 1)

99

array([74, 99])

array([[55, 56, 57, 58, 59],
       [65, 66, 67, 68, 69],
       [75, 76, 77, 78, 79],
       [85, 86, 87, 88, 89],
       [95, 96, 97, 98, 99]])

In [40]:
# max -----> maximum in array via axis = 0
array1D = np.array (range(50,100))
array2D = np.arange(50,100).reshape(2,25)
array3D = np.arange(50,100).reshape(5,2,5)
array1D.max()
array2D.max(axis = 0)
array3D.max(axis = 0)

99

array([75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
       92, 93, 94, 95, 96, 97, 98, 99])

array([[90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [41]:
# min -----> minimum in array
array1D = np.array (range(50,100))
array2D = np.arange(50,100).reshape(2,25)
array3D = np.arange(50,100).reshape(5,2,5)
array1D.min()
array2D.min()
array3D.min()

50

50

50

In [42]:
# min -----> minimum in array via axis = 1
array1D = np.array (range(50,100))
array2D = np.arange(50,100).reshape(2,25)
array3D = np.arange(50,100).reshape(5,2,5)
array1D.min()
array2D.min(axis = 1)
array3D.min(axis = 1)

50

array([50, 75])

array([[50, 51, 52, 53, 54],
       [60, 61, 62, 63, 64],
       [70, 71, 72, 73, 74],
       [80, 81, 82, 83, 84],
       [90, 91, 92, 93, 94]])

In [43]:
# min -----> minimum in array via axis = 0
array1D = np.array (range(50,100))
array2D = np.arange(50,100).reshape(2,25)
array3D = np.arange(50,100).reshape(5,2,5)
array1D.min()
array2D.min(axis = 0)
array3D.min(axis = 0)

50

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74])

array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [44]:
# sum -----> sum of all elements
array1D = np.array (range(50,100))
array2D = np.arange(50,100).reshape(2,25)
array3D = np.arange(50,100).reshape(5,2,5)
array1D.sum()
array2D.sum()
array3D.sum()

3725

3725

3725

In [45]:
# sum -----> sum of elements in array via axis = 1
array1D = np.array (range(50,100))
array2D = np.arange(50,100).reshape(2,25)
array3D = np.arange(50,100).reshape(5,2,5)
array1D.sum()
array2D.sum(axis = 1)
array3D.sum(axis = 1)

3725

array([1550, 2175])

array([[105, 107, 109, 111, 113],
       [125, 127, 129, 131, 133],
       [145, 147, 149, 151, 153],
       [165, 167, 169, 171, 173],
       [185, 187, 189, 191, 193]])

In [46]:
# sum -----> sum of elements in array via axis = 0
array1D = np.array (range(50,100))
array2D = np.arange(50,100).reshape(2,25)
array3D = np.arange(50,100).reshape(5,2,5)
array1D.sum()
array2D.sum(axis = 0)
array3D.sum(axis = 0)

3725

array([125, 127, 129, 131, 133, 135, 137, 139, 141, 143, 145, 147, 149,
       151, 153, 155, 157, 159, 161, 163, 165, 167, 169, 171, 173])

array([[350, 355, 360, 365, 370],
       [375, 380, 385, 390, 395]])

In [47]:
# mean -----> sum of all elements divided by size of elements
array1D = np.array (range(50,100))
array2D = np.arange(50,100).reshape(2,25)
array3D = np.arange(50,100).reshape(5,2,5)
array1D.mean()
array2D.mean()
array3D.mean()

74.5

74.5

74.5

In [48]:
# median -----> average of the middle elements
array1D = np.array (range(50,100))
array2D = np.arange(50,100).reshape(2,25)
array3D = np.arange(50,100).reshape(5,2,5)
np.median(array1D)
np.median(array2D)
np.median(array3D)

74.5

74.5

74.5

In [49]:
# varience -----> sum of (x-u)**2 divided by n
array1D = np.array (range(50,100))
array2D = np.arange(50,100).reshape(2,25)
array3D = np.arange(50,100).reshape(5,2,5)
np.var(array1D)
np.var(array2D)
np.var(array3D)

208.25

208.25

208.25

In [50]:
# standard deviation -----> sqrt of (sum of (x-u)**2 divided by n)
array1D = np.array (range(50,100))
array2D = np.arange(50,100).reshape(2,25)
array3D = np.arange(50,100).reshape(5,2,5)
np.std(array1D)
np.std(array2D)
np.std(array3D)

14.430869689661812

14.430869689661812

14.430869689661812

### STACKING and SPLITTING

In [51]:
# vstack -----> vertical attachment (columns are equal in 2 arrays)
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = np.array([[11,12,13],[14,15,16]])
np.vstack((array1,array2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16]])

In [52]:
# hstack -----> horizontal attachment (rows are equal in 2 arrays)
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = np.array([[11,12,13],[14,15,16],[17,18,19]])
np.hstack((array1,array2))

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [53]:
# dstack -----> parllel elements in 2 arrays along the third axis (min 3D array is required)
array1 = np.array([1,2,3])
array2 = np.array([11,12,13])
np.dstack((array1,array2))
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = np.array([[11,12,13],[14,15,16],[17,18,19]])
np.dstack((array1,array2))

array([[[ 1, 11],
        [ 2, 12],
        [ 3, 13]]])

array([[[ 1, 11],
        [ 2, 12],
        [ 3, 13]],

       [[ 4, 14],
        [ 5, 15],
        [ 6, 16]],

       [[ 7, 17],
        [ 8, 18],
        [ 9, 19]]])

In [54]:
# hsplit -----> horizontal split means dividing columns 
array2D = np.arange(50,100).reshape(2,25)
np.hsplit(array2D,5)

[array([[50, 51, 52, 53, 54],
        [75, 76, 77, 78, 79]]),
 array([[55, 56, 57, 58, 59],
        [80, 81, 82, 83, 84]]),
 array([[60, 61, 62, 63, 64],
        [85, 86, 87, 88, 89]]),
 array([[65, 66, 67, 68, 69],
        [90, 91, 92, 93, 94]]),
 array([[70, 71, 72, 73, 74],
        [95, 96, 97, 98, 99]])]

In [55]:
# vsplit -----> vertical split means dividing rows 
array2D = np.arange(50,100).reshape(2,25)
np.vsplit(array2D,1)

[array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
         66, 67, 68, 69, 70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
         91, 92, 93, 94, 95, 96, 97, 98, 99]])]

In [56]:
# where -----> returns values with some conditions
array2D = np.arange(50,100).reshape(2,25)
np.where(array2D%5==0, array2D , 'False')

array([['50', 'False', 'False', 'False', 'False', '55', 'False', 'False',
        'False', 'False', '60', 'False', 'False', 'False', 'False', '65',
        'False', 'False', 'False', 'False', '70', 'False', 'False',
        'False', 'False'],
       ['75', 'False', 'False', 'False', 'False', '80', 'False', 'False',
        'False', 'False', '85', 'False', 'False', 'False', 'False', '90',
        'False', 'False', 'False', 'False', '95', 'False', 'False',
        'False', 'False']], dtype='<U11')

### SET OPERATIONS

In [57]:
# union1d -----> combining
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = np.array([[11,12,13],[14,15,16],[17,18,19]])
np.union1d(array1,array2)
np.union1d(array2,array1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [58]:
# intersect1d -----> common
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = np.array([[11,12,13],[14,15,16],[17,18,19]])
np.intersect1d(array1,array2)
np.intersect1d(array2,array1)

array([], dtype=int32)

array([], dtype=int32)

In [59]:
# setdiff1d -----> subtracting array2 from array1 and printing remaining elements in array1
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = np.array([[11,12,13],[14,15,16],[17,18,19]])
np.setdiff1d(array1,array2)
np.setdiff1d(array2,array1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

### ARITHMETIC OPERATIONS

In [60]:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = np.array([[11,12,13],[14,15,16],[17,18,19]])
array1 + array2
array1 - array2
array1 * array2
array1 / array2
array1 // array2
array1 % array2
array1 @ array2

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

array([[0.09090909, 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     ],
       [0.41176471, 0.44444444, 0.47368421]])

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

### AGGREGATE FUNCTIONS

In [61]:
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a2 = np.array([[11,12,13],[14,15,16],[17,18,19]])
np.add(a1,a2)
np.subtract(a1,a2)
np.multiply(a1,a2)
np.matmul(a1,a2)

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

### append and concatenate

In [62]:
# append -----> adding at the last of the array
# concatenate -----> adding in left-right or up-down direction
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a2 = np.array([[11,12,13],[14,15,16],[17,18,19]])
np.append(a1,a2)
np.append(a1,a2,axis = 1)
np.append(a1,a2,axis = 0)
np.concatenate((a1,a2))
np.concatenate((a1,a2) , axis = 1)
np.concatenate((a1,a2) , axis = 0)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

### FILTERING ARRAYS

In [63]:
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a2 = np.array([[11,12,13],[14,15,16],[17,18,19]])
a1 > 5
a2 < 15

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

### NUMPY RANDOM NUMBERS

In [64]:
# np.random.rand ----->
# generates an array with random numbers that are uniformly distributed between 0 and 1
array2D = np.random.rand(2,3)
array3D = np.random.rand(5,2,5)
array2D
array3D

array([[0.73852266, 0.13648889, 0.53915898],
       [0.52860591, 0.01443914, 0.09355033]])

array([[[0.34382799, 0.93264099, 0.8842311 , 0.64566173, 0.02377194],
        [0.95064584, 0.92935432, 0.3304532 , 0.07858602, 0.00227557]],

       [[0.96278648, 0.70421358, 0.896093  , 0.46503482, 0.46104691],
        [0.34854073, 0.5143381 , 0.37540582, 0.41779195, 0.06341905]],

       [[0.52734075, 0.27658989, 0.33342812, 0.13278614, 0.1366226 ],
        [0.89957934, 0.49498723, 0.05807134, 0.33452242, 0.12377241]],

       [[0.53870482, 0.16490694, 0.46532209, 0.5397041 , 0.29180749],
        [0.47948764, 0.26957061, 0.79508889, 0.96461773, 0.57594685]],

       [[0.24273544, 0.67983993, 0.98140218, 0.20445534, 0.51912131],
        [0.68808925, 0.67691453, 0.14367823, 0.22121446, 0.88537426]]])

In [65]:
# np.random.randn ----->
# generates an array with random numbers that are normally distributed with mean = 0 and sd = 1
array2D = np.random.randn(2,3)
array3D = np.random.randn(5,2,5)
array2D
array3D
np.mean(array2D)
np.mean(array3D)
np.std(array2D)
np.std(array3D)

array([[-0.72506201,  0.06380681, -1.17170102],
       [-0.29041479, -0.80791029,  0.75431523]])

array([[[-1.04106681, -3.45872432, -1.51654647, -0.27882771,
          0.5255089 ],
        [ 1.11986915, -0.33433952, -0.45037297, -0.88679849,
          0.08564817]],

       [[ 1.77658616,  2.06753251,  0.24787539, -0.06495301,
          0.33080563],
        [-0.46495403,  0.73533233, -1.09532582, -0.98189206,
          0.69421   ]],

       [[ 0.78167419, -0.59946266,  1.96972697,  0.75172213,
         -0.49426339],
        [-1.00418697,  1.16210844,  0.31208454, -3.19474494,
         -1.87584242]],

       [[-1.01575143,  1.81017348,  0.37335583,  0.94938586,
          0.50379988],
        [-0.59844129,  1.19464824, -0.43627001,  1.14315985,
         -1.12900401]],

       [[-0.97313904,  0.53601495,  2.51185635,  0.14398478,
          1.79497811],
        [ 0.31792922,  0.81938158,  0.7922813 , -0.50044306,
         -1.92899465]]])

-0.3628276781156079

0.022545777474002424

0.6349353269041779

1.2426215097892228

In [66]:
# np.random.randint ----->
# generates an array with random numbers that are uniformly distributed between 0 and given integer
array2D = np.random.randint(50 , size = (2,3))
array3D = np.random.randint(50 , size = (5,2,5))
array2D
array3D
array2D = np.random.randint(50,100 , size = (2,3))
array3D = np.random.randint(50,100 , size = (5,2,5))
array2D
array3D

array([[22, 49, 34],
       [48, 35, 36]])

array([[[16, 37, 38, 12, 39],
        [ 4, 15,  9, 38, 39]],

       [[15, 39,  2, 28, 17],
        [49,  5,  8,  0, 28]],

       [[46, 34, 20, 24, 25],
        [13, 42, 21,  2, 35]],

       [[23, 12,  7, 25, 33],
        [ 8, 45,  8, 13, 20]],

       [[11, 21,  8, 37,  2],
        [ 0, 17, 14, 16, 17]]])

array([[74, 55, 74],
       [77, 80, 65]])

array([[[60, 84, 60, 58, 51],
        [66, 81, 73, 76, 86]],

       [[65, 94, 95, 76, 75],
        [89, 59, 66, 80, 59]],

       [[67, 97, 58, 87, 85],
        [62, 78, 82, 70, 64]],

       [[97, 71, 85, 71, 56],
        [55, 52, 62, 73, 78]],

       [[91, 84, 72, 70, 82],
        [81, 71, 94, 86, 64]]])

In [67]:
# np.random.uniform ----->
# generates array with random numbers that are uniformly distributed within the given range of values
array2D = np.random.uniform(50,60 , size = (2,3))
array3D = np.random.uniform(50,60 , size = (5,2,5))
array2D
array3D

array([[58.08107549, 59.19999339, 50.4455265 ],
       [59.53420965, 57.62848807, 52.49294163]])

array([[[56.33484997, 51.36593366, 50.12284963, 50.90397347,
         51.64151352],
        [54.48805357, 50.24061128, 59.12978629, 53.59953142,
         58.24837312]],

       [[59.33309958, 53.60847997, 58.08756768, 55.09026226,
         54.63170511],
        [58.32622648, 57.86718979, 57.97612955, 51.75422559,
         54.09754091]],

       [[50.62929404, 55.46738389, 59.51742497, 58.18127459,
         52.20092921],
        [57.85686147, 54.84606342, 58.27986889, 51.28433562,
         53.98837771]],

       [[57.72848316, 57.25488931, 59.03889523, 56.9631553 ,
         58.7395658 ],
        [51.39892037, 52.67807507, 54.71100669, 56.59577328,
         55.23045266]],

       [[58.9087324 , 55.30114271, 59.79107167, 51.93925366,
         59.7970863 ],
        [59.16856338, 50.12710831, 52.07736615, 57.20029033,
         55.11662641]]])

In [68]:
# np.random.seed ----->
# puts the random values constant even though we execute the random code for multiple times
np.random.seed(1372)
array2D = np.random.randint(50 , size = (2,3))
array3D = np.random.randint(50 , size = (5,2,5))
array2D
array3D

array([[20,  2, 42],
       [ 7, 25, 46]])

array([[[19, 18, 44, 36, 14],
        [ 5, 36, 29, 30,  5]],

       [[ 7,  1, 22, 16, 15],
        [25, 28, 22, 42, 39]],

       [[16, 10, 35, 41, 47],
        [12, 29, 11, 40, 39]],

       [[15,  9, 20, 21, 10],
        [43, 39, 38, 49, 21]],

       [[45, 23, 40,  5, 46],
        [ 3, 21, 37, 35, 16]]])

### EXPANDING AND SQUEEZING

In [69]:
# expand_dims() ----->
# can add a new axis to an array using the expand_dims() method 
# by providing the array and the axis along which to expand
a1 = np.array([1,2,3,4,5,6,7,8,9])
a1
a1.ndim
a2 = np.expand_dims(a1 , axis = 0)
a2
a2.ndim
a2 = np.expand_dims(a1 , axis = 1)
a2
a2.ndim

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

1

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

2

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

2

In [70]:
# squeeze() -----> removes the axis that has a single entry
a1 = np.array([[[1,2,3,4,5,6,7,8,9]]])
a1
a1.ndim
a2 = np.squeeze(a1 , axis = 0)
a2
a2.ndim
a2 = np.squeeze(a1 , axis = 1)
a2
a2.ndim

array([[[1, 2, 3, 4, 5, 6, 7, 8, 9]]])

3

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

2

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

2